apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
      - name: azure-vote-back
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: {{ .Values.redis.ports.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: {{ .Values.redis.ports.containerPort }}
  selector:
    app: azure-vote-back