frontend:
  image:
    repository: acrunyleyalucasgrando.azurecr.io/azure-vote-front
    tag: "26"              # <<< substitua pelo número do build/tag que você quer usar
  ports:
    containerPort: 80

redis:
  image:
    repository: mcr.microsoft.com/oss/bitnami/redis
    tag: "6.0.8"
  ports:
    containerPort: 6379
